services:
  patients_tracker:
    build: .
    image: ptracker
    container_name: patients_tracker
    environment:
      BOT_TOKEN: your_bot_token
      DB_LOCATION: ./db/patients.db
      TZ: Europe/Moscow
    volumes:
      - ./db:/app/db
    restart: always
    labels:
      log_type: "json"
